const express = require('express');
const SchemeController = require('../controllers/SchemeController');
const router = express.Router();
router.get('/search', SchemeController.search);
router.get('/categories', SchemeController.getCategories);
router.get('/featured', SchemeController.featured);
router.get('/latest', SchemeController.latest);
router.get('/', SchemeController.list);
router.get('/:id', SchemeController.getById);
module.exports = router;
