class StringsTe {
  static const Map<String, String> map = {
    'appName': 'అగ్రిసాథి AI',
    'appTagline': 'మీ AI వ్యవసాయ సహాయకుడు',
    'welcomeTitle': 'అగ్రిసాథి AI కి స్వాగతం',
    'welcomeSubtitle': 'ప్రతి రైతుకు ప్రభుత్వ పథకాలు మరియు AI సహాయాన్ని సులభతరం చేయడం.',
    'onboarding1Title': 'ప్రభుత్వ పథకాలను కనుగొనండి',
    'onboarding1Desc': 'మీ పొలానికి తగిన రాయితీలు, పంట భీమా మరియు ఆర్థిక సహాయాన్ని కనుగొనండి.',
    'onboarding2Title': 'అర్హతను తక్షణమే తనిఖీ చేయండి',
    'onboarding2Desc': 'కొన్ని సులభమైన ప్రశ్నలకు సమాధానమిచ్చి మీరు ఏ పథకాలకు అర్హులో తెలుసుకోండి.',
    'onboarding3Title': 'AI చాట్ & వాయిస్ అసిస్టెంట్',
    'onboarding3Desc': 'మీ భాషలో ప్రశ్నలు అడగండి, PDF పత్రాలను అప్‌లోడ్ చేయండి మరియు సులభమైన సమాధానాలు పొందండి.',
    'getStarted': 'ప్రారంభించండి',
    'next': 'తరువాత',
    'skip': 'దాటవేయి',
    'back': 'వెనుకకు',
    'loginTitle': 'రైతు లాగిన్ / సైన్ అప్',
    'loginSubtitle': 'OTP పొందడానికి మీ మొబైల్ సంఖ్యను నమోదు చేయండి',
    'phoneNumber': 'మొబైల్ సంఖ్య',
    'sendOtp': 'OTP పంపండి',
    'home': 'హోమ్',
    'schemes': 'పథకాలు',
    'aiChat': 'AI చాట్',
    'eligibilityChecker': 'అర్హత తనిఖీ',
    'pdfExplainer': 'PDF వివరణ',
    'bookmarks': 'సేవ్ చేసినవి',
    'notifications': 'నోటిఫికేషన్లు',
    'profile': 'ప్రొఫైల్',
    'settings': 'సెట్టింగ్‌లు',
    'adminPanel': 'అడ్మిన్ ప్యానెల్',
    'language': 'భాష',
    'selectLanguage': 'మీ భాషను ఎంచుకోండి',
    'searchPlaceholder': 'పథకాలు, రాయితీలను శోధించండి లేదా ఏదైనా అడగండి...',
    'retry': 'మళ్లీ ప్రయత్నించండి',
    'errorOccurred': 'ఏదో పొరపాటు జరిగింది',
    'noDataFound': 'డేటా కనుగొనబడలేదు',
    'themeMode': 'థీమ్ మోడ్',
    'lightTheme': 'లైట్ థీమ్',
    'darkTheme': 'డార్క్ థీమ్',
    'systemDefault': 'సిస్టమ్ డిఫాల్ట్',
  };
}
