class StringsKn {
  static const Map<String, String> map = {
    'appName': 'ಅಗ್ರಿಸಾಥಿ AI',
    'appTagline': 'ನಿಮ್ಮ AI ಕೃಷಿ ಸಹಾಯಕ',
    'welcomeTitle': 'ಅಗ್ರಿಸಾಥಿ AI ಗೆ ಸುಸ್ವಾಗತ',
    'welcomeSubtitle': 'ಪ್ರತಿಯೊಬ್ಬ ರೈತರಿಗೂ ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು ಮತ್ತು AI ಸಹಾಯವನ್ನು ಸರಳಗೊಳಿಸುವುದು.',
    'onboarding1Title': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳನ್ನು ಕಂಡುಕೊಳ್ಳಿ',
    'onboarding1Desc': 'ನಿಮ್ಮ ಜಮೀನಿಗೆ ಸೂಕ್ತವಾದ ಸಬ್ಸಿಡಿಗಳು, ಬೆಳೆ ವಿಮೆ ಮತ್ತು ಆರ್ಥಿಕ ನೆರವು ಪಡೆಯಿರಿ.',
    'onboarding2Title': 'ಅರ್ಹತೆಯನ್ನು ತಕ್ಷಣ ಪರಿಶೀಲಿಸಿ',
    'onboarding2Desc': 'ಕೆಲವು ಸರಳ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ ಮತ್ತು ನೀವು ಯಾವ ಯೋಜನೆಗಳಿಗೆ ಅರ್ಹರು ಎಂಬುದನ್ನು ತಿಳಿಯಿರಿ.',
    'onboarding3Title': 'AI ಚಾಟ್ ಮತ್ತು ವಾಯ್ಸ್ ಅಸಿಸ್ಟೆಂಟ್',
    'onboarding3Desc': 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಪ್ರಶ್ನೆಗಳನ್ನು ಕೇಳಿ, PDF ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಸರಳ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ.',
    'getStarted': 'ಪ್ರಾರಂಭಿಸಿ',
    'next': 'ಮುಂದೆ',
    'skip': 'ಸ್ಕಿಪ್ ಮಾಡಿ',
    'back': 'ಹಿಂದೆ',
    'loginTitle': 'ರೈತ ಲಾಗಿನ್ / ಸೈನ್ ಅಪ್',
    'loginSubtitle': 'OTP ಪಡೆಯಲು ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ',
    'phoneNumber': 'ಮೊಬೈಲ್ ಸಂಖ್ಯೆ',
    'sendOtp': 'OTP ಕಳುಹಿಸಿ',
    'home': 'ಹೋಮ್',
    'schemes': 'ಯೋಜನೆಗಳು',
    'aiChat': 'AI ಚಾಟ್',
    'eligibilityChecker': 'ಅರ್ಹತಾ ಪರಿಶೀಲಕ',
    'pdfExplainer': 'PDF ವಿವರಣೆ',
    'bookmarks': 'ಉಳಿಸಿದವು',
    'notifications': 'ಸೂಚನೆಗಳು',
    'profile': 'ಪ್ರೊಫೈಲ್',
    'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'adminPanel': 'ಅಡ್ಮಿನ್ ಪ್ಯಾನೆಲ್',
    'language': 'ಭಾಷೆ',
    'selectLanguage': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'searchPlaceholder': 'ಯೋಜನೆಗಳು, ಸಬ್ಸಿಡಿಗಳನ್ನು ಹುಡುಕಿ ಅಥವಾ ಏನನ್ನಾದರೂ ಕೇಳಿ...',
    'retry': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    'errorOccurred': 'ಏನೋ ತಪ್ಪಾಗಿದೆ',
    'noDataFound': 'ಯಾವುದೇ ಡೇಟಾ ಕಂಡುಬಂದಿಲ್ಲ',
    'themeMode': 'ಥೀಮ್ ಮೋಡ್',
    'lightTheme': 'ಲೈಟ್ ಥೀಮ್',
    'darkTheme': 'ಡಾರ್ಕ್ ಥೀಮ್',
    'systemDefault': 'ಸಿಸ್ಟಮ್ ಡಿಫಾಲ್ಟ್',
  };
}
