class StringsEn {
  static const Map<String, String> map = {
    'appName': 'KrishiSahayak',
    'appTagline': 'Your AI Agricultural Assistant',
    'welcomeTitle': 'Welcome to KrishiSahayak',
    'welcomeSubtitle': 'Simplifying government schemes and AI assistance for every farmer.',
    'onboarding1Title': 'Discover Government Schemes',
    'onboarding1Desc': 'Find subsidies, crop insurance, and financial support tailored to your farm.',
    'onboarding2Title': 'Check Eligibility Instantly',
    'onboarding2Desc': 'Answer a few simple questions to know which schemes you qualify for.',
    'onboarding3Title': 'AI Chat & Voice Assistant',
    'onboarding3Desc': 'Ask questions in your language, upload PDF documents, and get simple answers.',
    'getStarted': 'Get Started',
    'next': 'Next',
    'skip': 'Skip',
    'back': 'Back',
    'loginTitle': 'Farmer Login / Signup',
    'loginSubtitle': 'Enter your mobile number to receive OTP',
    'phoneNumber': 'Mobile Number',
    'sendOtp': 'Send OTP',
    'home': 'Home',
    'schemes': 'Schemes',
    'aiChat': 'AI Chat',
    'eligibilityChecker': 'Eligibility Checker',
    'pdfExplainer': 'PDF Explainer',
    'bookmarks': 'Bookmarks',
    'notifications': 'Notifications',
    'profile': 'Profile',
    'settings': 'Settings',
    'adminPanel': 'Admin Panel',
    'language': 'Language',
    'selectLanguage': 'Select Your Language',
    'searchPlaceholder': 'Search schemes, subsidies, or ask anything...',
    'retry': 'Retry',
    'errorOccurred': 'Something went wrong',
    'noDataFound': 'No data found',
    'themeMode': 'Theme Mode',
    'lightTheme': 'Light Theme',
    'darkTheme': 'Dark Theme',
    'systemDefault': 'System Default',
  };
}
