class StringsMr {
  static const Map<String, String> map = {
    'appName': 'ॲग्रीसाथी एआय',
    'appTagline': 'तुमचा एआय शेती सहाय्यक',
    'welcomeTitle': 'ॲग्रीसाथी एआय मध्ये आपले स्वागत आहे',
    'welcomeSubtitle': 'प्रत्येक शेतकऱ्यासाठी सरकारी योजना आणि एआय मदत सुलभ करणे.',
    'onboarding1Title': 'सरकारी योजना शोधा',
    'onboarding1Desc': 'तुमच्या शेतीसाठी योग्य अनुदाने, पीक विमा आणि आर्थिक मदत शोधा.',
    'onboarding2Title': 'पात्रता त्वरित तपासा',
    'onboarding2Desc': 'काही सोप्या प्रश्नांची उत्तरे द्या आणि तुम्ही कोणत्या योजनेसाठी पात्र आहात ते जाणून घ्या.',
    'onboarding3Title': 'एआय चॅट आणि व्हॉइस असिस्टंट',
    'onboarding3Desc': 'तुमच्या स्वतःच्या भाषेत प्रश्न विचारा, पीडीएफ कागदपत्रे अपलोड करा आणि सोपी उत्तरे मिळवा.',
    'getStarted': 'सुरू करा',
    'next': 'पुढे',
    'skip': 'वगळा',
    'back': 'मागे',
    'loginTitle': 'शेतकरी लॉगिन / साइनअप',
    'loginSubtitle': 'ओटीपी मिळवण्यासाठी तुमचा मोबाईल नंबर प्रविष्ट करा',
    'phoneNumber': 'मोबाईल नंबर',
    'sendOtp': 'ओटीपी पाठवा',
    'home': 'मुख्यपृष्ठ',
    'schemes': 'योजना',
    'aiChat': 'एआय चॅट',
    'eligibilityChecker': 'पात्रता तपासणी',
    'pdfExplainer': 'पीडीएफ स्पष्टीकरण',
    'bookmarks': 'जतन केलेले',
    'notifications': 'सूचना',
    'profile': 'प्रोफाइल',
    'settings': 'सेटिंग्ज',
    'adminPanel': 'ॲडमिन पॅनेल',
    'language': 'भाषा',
    'selectLanguage': 'तुमची भाषा निवडा',
    'searchPlaceholder': 'योजना, अनुदान शोधा किंवा काहीही विचारा...',
    'retry': 'पुन्हा प्रयत्न करा',
    'errorOccurred': 'काहीतरी त्रुटी झाली',
    'noDataFound': 'कोणतीही माहिती आढळली नाही',
    'themeMode': 'थीम मोड',
    'lightTheme': 'लाइट थीम',
    'darkTheme': 'डार्क थीम',
    'systemDefault': 'सिस्टम डीफॉल्ट',
  };
}
