class StringsHi {
  static const Map<String, String> map = {
    'appName': 'एग्रीसाथी एआई',
    'appTagline': 'आपका एआई कृषि सहायक',
    'welcomeTitle': 'एग्रीसाथी एआई में आपका स्वागत है',
    'welcomeSubtitle': 'हर किसान के लिए सरकारी योजनाओं और एआई सहायता को आसान बनाना।',
    'onboarding1Title': 'सरकारी योजनाएं खोजें',
    'onboarding1Desc': 'अपने खेत के अनुसार सब्सिडी, फसल बीमा और वित्तीय सहायता पाएं।',
    'onboarding2Title': 'पात्रता की तुरंत जांच करें',
    'onboarding2Desc': 'कुछ सरल प्रश्नों के उत्तर दें और जानें कि आप किन योजनाओं के पात्र हैं।',
    'onboarding3Title': 'एआई चैट और वॉइस असिस्टेंट',
    'onboarding3Desc': 'अपनी भाषा में प्रश्न पूछें, पीडीएफ दस्तावेज़ अपलोड करें और सरल उत्तर पाएं।',
    'getStarted': 'शुरू करें',
    'next': 'आगे बढ़ें',
    'skip': 'छोड़ें',
    'back': 'पीछे',
    'loginTitle': 'किसान लॉगिन / साइनअप',
    'loginSubtitle': 'ओटीपी प्राप्त करने के लिए अपना मोबाइल नंबर दर्ज करें',
    'phoneNumber': 'मोबाइल नंबर',
    'sendOtp': 'ओटीपी भेजें',
    'home': 'होम',
    'schemes': 'योजनाएं',
    'aiChat': 'एआई चैट',
    'eligibilityChecker': 'पात्रता जांचकर्ता',
    'pdfExplainer': 'पीडीएफ समझाएं',
    'bookmarks': 'सहेजे गए',
    'notifications': 'सूचनाएं',
    'profile': 'प्रोफाइल',
    'settings': 'सेटिंग्स',
    'adminPanel': 'एडमिन पैनल',
    'language': 'भाषा',
    'selectLanguage': 'अपनी भाषा चुनें',
    'searchPlaceholder': 'योजनाएं, सब्सिडी खोजें या कुछ भी पूछें...',
    'retry': 'पुनः प्रयास करें',
    'errorOccurred': 'कुछ गलत हो गया',
    'noDataFound': 'कोई डेटा नहीं मिला',
    'themeMode': 'थीम मोड',
    'lightTheme': 'लाइट थीम',
    'darkTheme': 'डार्क थीम',
    'systemDefault': 'सिस्टम डिफ़ॉल्ट',
  };
}
