class StringsGu {
  static const Map<String, String> map = {
    'appName': 'એગ્રીસાથી એઆઈ',
    'appTagline': 'તમારો એઆઈ કૃષિ મદદગાર',
    'welcomeTitle': 'એગ્રીસાથી એઆઈ માં તમારું સ્વાગત છે',
    'welcomeSubtitle': 'દરેક ખેડૂત માટે સરકારી યોજનાઓ અને એઆઈ મદદ સરળ બનાવવી.',
    'onboarding1Title': 'સરકારી યોજનાઓ શોધો',
    'onboarding1Desc': 'તમારા ખેતર માટે સબસિડી, પાક વીમો અને નાણાકીય સહાય શોધો.',
    'onboarding2Title': 'પાત્રતા તરત જ તપાસો',
    'onboarding2Desc': 'કેટલાક સરળ પ્રશ્નોના જવાબ આપો અને જાણો કે તમે કઈ યોજના માટે પાત્ર છો.',
    'onboarding3Title': 'એઆઈ ચેટ અને વોઈસ અસિસ્ટન્ટ',
    'onboarding3Desc': 'તમારી ભાષામાં પ્રશ્નો પૂછો, પીડીએફ દસ્તાવેજો અપલોડ કરો અને સરળ જવાબો મેળવો.',
    'getStarted': 'શરૂ કરો',
    'next': 'આગળ',
    'skip': 'છોડો',
    'back': 'પાછળ',
    'loginTitle': 'ખેડૂત લોગિન / સાઇનઅપ',
    'loginSubtitle': 'ઓટીપી મેળવવા માટે તમારો મોબાઈલ નંબર દાખલ કરો',
    'phoneNumber': 'મોબાઈલ નંબર',
    'sendOtp': 'ઓટીપી મોકલો',
    'home': 'હોમ',
    'schemes': 'યોજનાઓ',
    'aiChat': 'એઆઈ ચેટ',
    'eligibilityChecker': 'પાત્રતા તપાસનાર',
    'pdfExplainer': 'પીડીએફ સમજો',
    'bookmarks': 'સેવ કરેલ',
    'notifications': 'સૂચનાઓ',
    'profile': 'પ્રોફાઇલ',
    'settings': 'સેટિંગ્સ',
    'adminPanel': 'એડમિન પેનલ',
    'language': 'ભાષા',
    'selectLanguage': 'તમારી ભાષા પસંદ કરો',
    'searchPlaceholder': 'યોજનાઓ, સબસિડી શોધો અથવા કંઈપણ પૂછો...',
    'retry': 'ફરી પ્રયાસ કરો',
    'errorOccurred': 'કંઈક ખોટું થયું',
    'noDataFound': 'કોઈ ડેટા મળ્યો નથી',
    'themeMode': 'થીમ મોડ',
    'lightTheme': 'લાઇટ થીમ',
    'darkTheme': 'ડાર્ક થીમ',
    'systemDefault': 'સિસ્ટમ ડિફોલ્ટ',
  };
}
